# Start from a balena python3 image; build version is needed for RPi.GPIO
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-latest-build

RUN pip install rak811

COPY pyrak811-balena.py /opt/rak811/

WORKDIR /opt/rak811

CMD ["./pyrak811-balena.py"]

